In [1]:
import pandas as pd

In [49]:
test=pd.read_csv(r'C:\Users\sarve\Downloads\Automobile_data.csv')

In [50]:
test

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [51]:
#From the given dataset print the first and last five rows

In [52]:
test.head(5)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [53]:
test.head(5)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [54]:
test.tail(5)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [55]:
#Clean the dataset and update the CSV file

In [56]:
test.replace(['0','?', 'n.a','NaN'],'NA')

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [57]:
#fina expensive car

In [58]:
test2

          company    price
35  mercedes-benz  45400.0

In [59]:
#checking maximum value in single column
check_max_price=test['price'].max()
check_max_price

45400.0

In [60]:
#checking count of single column

In [61]:
check_count=test['company'].count()
check_count

61

In [62]:
print(check_count)

61

In [63]:
test.shape

(61, 10)

In [64]:
#check unique values

In [66]:
len(test['price'])

61

In [75]:
test3=test[test['price']>13495]

In [76]:
test3

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
5,5,audi,sedan,99.8,177.3,ohc,five,110,19,15250.0
6,6,audi,wagon,105.8,192.7,ohc,five,110,19,18920.0
7,9,bmw,sedan,101.2,176.8,ohc,four,101,23,16430.0
8,10,bmw,sedan,101.2,176.8,ohc,four,101,23,16925.0
9,11,bmw,sedan,101.2,176.8,ohc,six,121,21,20970.0
10,13,bmw,sedan,103.5,189.0,ohc,six,182,16,30760.0
11,14,bmw,sedan,103.5,193.8,ohc,six,182,16,41315.0
12,15,bmw,sedan,110.0,197.0,ohc,six,182,15,36880.0
24,33,jaguar,sedan,113.0,199.6,dohc,six,176,15,32250.0
25,34,jaguar,sedan,113.0,199.6,dohc,six,176,15,35550.0
26,35,jaguar,sedan,102.0,191.7,ohcv,twelve,262,13,36000.0
31,43,mazda,sedan,104.9,175.0,ohc,four,72,31,18344.0
32,44,mercedes-benz,sedan,110.0,190.9,ohc,five,123,22,25552.0
33,45,mercedes-benz,wagon,110.0,190.9,ohc,five,123,22,28248.0
34,46,mercedes-benz,sedan,120.9,208.1,ohcv,eight,184,14,40960.0
35,47,mercedes-benz,hardtop,112.0,199.2,ohcv,eight,184,14,45400.0
44,57,nissan,sedan,100.4,184.6,ohcv,six,152,19,13499.0
45,61,porsche,hardtop,89.5,168.9,ohcf,six,207,17,34028.0
46,62,porsche,convertible,89.5,168.9,ohcf,six,207,17,37028.0
54,79,toyota,wagon,104.5,187.8,dohc,six,156,19,15750.0

In [80]:
#check for null
test5=(test['engine-type'].isna().sum())
test5

0