In [4]:
counter = 5
while counter >= 1:
    print(f"time remaining {counter} secounds..!!")
    counter-=1
print("Time's up")

time remaining 5 secounds..!!
time remaining 4 secounds..!!
time remaining 3 secounds..!!
time remaining 2 secounds..!!
time remaining 1 secounds..!!
Time's up

In [ ]:
#Checking counter with while loop

In [9]:
def check_timer(counter):
 while counter >= 1:
    print(f"time remaining {counter} secounds..!!")
    counter-=1
 print("Time's up")

check_timer(10)

time remaining 10 secounds..!!
time remaining 9 secounds..!!
time remaining 8 secounds..!!
time remaining 7 secounds..!!
time remaining 6 secounds..!!
time remaining 5 secounds..!!
time remaining 4 secounds..!!
time remaining 3 secounds..!!
time remaining 2 secounds..!!
time remaining 1 secounds..!!
Time's up

In [ ]:
#title method use

In [25]:
str = "pynative.com is for python lovers"
capitalized_str = str.title()
print(capitalized_str)

Pynative.Com Is For Python Lovers

In [34]:
test=input("Enter the string")
digi_check =False
for i in test:
    if i.isdigit():
        digi_check=True
        break

if digi_check:
    print("The string contains at least one digit.")
else:
    print("The string does not contain any digits.")

Enter the string test8

The string contains at least one digit.

In [60]:
i=5
while i>=1:
    print("*"*i)
    i-=1

*****
****
***
**
*

In [ ]:
del str

In [1]:
i = 5
while i >= 1:
    print(str(i)*i)
    i -= 1

55555
4444
333
22
1

In [7]:
i=1
while i>=5:
    print(i)
    i+=1

In [8]:
print("hello")

hello

In [12]:
i=1
while i<=5:
    print(str(i)*i)
    i+=1

1
22
333
4444
55555

In [ ]:
#Test for Leap Year

In [9]:
test= int(input("enter the year"))
if test % 4 == 0:
    print("its a leap year")
else:
    print("not a leap year")

enter the year 2016

its a leap year

In [15]:
#Test for fibonaacci series
test =int(input("enter a number"))
first=0
nextnum=1
total=0 
while total <=test:
    print(total)
    total=first+nextnum
    first=nextnum
    nextnum=total

enter a number 100

0
1
2
3
5
8
13
21
34
55
89

In [2]:
#check for palimdrome or not
test=input("Enter the string to check")
newstring=test[::-1]
if newstring == test:
    print("Palindrome")
else:
    print("Not a Palindrome")

Enter the string to check 887779

Not a Palindrome

In [6]:
i=5
while i >=1 :
    print("x"*i)
    i-=1

xxxxx
xxxx
xxx
xx
x

In [ ]:
#Single table printing

In [14]:
i =2
for j in range(1,11):
    print(i*j)

2
4
6
8
10
12
14
16
18
20

In [29]:
#Multiple tables
for i in range(1,11):
    for j in range(1,11):
        print(i*j,end=" ")
    print(" ")

1 2 3 4 5 6 7 8 9 10
2 4 6 8 10 12 14 16 18 20
3 6 9 12 15 18 21 24 27 30
4 8 12 16 20 24 28 32 36 40
5 10 15 20 25 30 35 40 45 50
6 12 18 24 30 36 42 48 54 60
7 14 21 28 35 42 49 56 63 70
8 16 24 32 40 48 56 64 72 80
9 18 27 36 45 54 63 72 81 90
10 20 30 40 50 60 70 80 90 100

In [40]:
#rever the digits with space

test=input("enter the number")
tests2=test[::-1]
for i in tests2:
    print(i+" ",end=" ")

enter the number 7899

9  9  8  7

In [47]:
#merge list
list1=[1,2,3,4]
list2=[5,6,7,8]
list1.extend(list2)
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8]

In [48]:
#pattern print
i=1
while i<=5:
    print((str(i)+" ")*i)
    i+=1

1
2 2
3 3 3
4 4 4 4
5 5 5 5 5

In [49]:
#count the appearance
test="emma is good girl is nice friend"
cnt=test.count("is")
print(cnt)

2

In [53]:
#display the number divisible by 5
list1=[10,20,33,46,55]
for i in list1:
    if i % 5 == 0:
        print(f"divible by 5 numbe is ={i}" )
    else:
        print("Not divisible")

divible by 5 numbe is =10
divible by 5 numbe is =20
Not divisible
Not divisible
divible by 5 numbe is =55

In [4]:
#check the first and last number of the list are same

list1=[10,20,30,40,10]
first=list1[0]
last=list1[-1]
if first == last:
    print("same")
else:
    print("not same")

same

In [19]:
import pandas as pd
df=pd.read_excel(r"Collage_Option_List.xlsx")

C:\Users\sarve\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [9]:
pd.head()

,Sr No,UDISE,Area,District,College Name,College Type,Choice Code,Stream,Medium,Management Type,...,NTB,NTC,NTD,OBC,SBC,SEBC,EWS,Management,Inhouse,General
0,1,27230300325,MUMBAI_DYD_URC3 ( GHATKOPAR ) (272303),MUMBAI CITY/SUBURBAN,NATIONAL SARVODAYA JR COLLEGE OF COMMERCE AND...,Co-Ed,MU6873CGE,Commerce,English,Private Sanstha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,27230200235,MUMBAI_DYD_URC2 ( SION ) (272302),MUMBAI CITY/SUBURBAN,ABHYUDAYA EDUCATION SOCIETY'S HIGH SCHOOL (MAR...,Co-Ed,MU6792CGE,Commerce,English,Private Sanstha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,27230300307,MUMBAI_DYD_URC3 ( GHATKOPAR ) (272303),MUMBAI CITY/SUBURBAN,"AFAC ENGLISH SCHOOL , Justice Dudhat Chowk, M....",Co-Ed,MU6871CGE,Commerce,English,Private Sanstha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,27230500217,MUMBAI_DYD_URC5 ( ANDHERI ) (272305),MUMBAI CITY/SUBURBAN,"AIRPORT HIGH SCHOOL AND JUNIOR COLLEGE , New A...",Co-Ed,MU7069CGE,Commerce,English,Private Sanstha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,27230100966,MUMBAI_DYD_URC1 ( GRANT ROAD ) (272301),MUMBAI CITY/SUBURBAN,ANJUMAN-I-ISLAM'S AKBAR PEERBHOY COLLEGE OF CO...,Co-Ed,MU6748CGE,Commerce,English,Private Sanstha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df.head()

,Sr No,UDISE,Area,District,College Name,College Type,Choice Code,Stream,Medium,Management Type,...,NTB,NTC,NTD,OBC,SBC,SEBC,EWS,Management,Inhouse,General
0,1,27230300325,MUMBAI_DYD_URC3 ( GHATKOPAR ) (272303),MUMBAI CITY/SUBURBAN,NATIONAL SARVODAYA JR COLLEGE OF COMMERCE AND...,Co-Ed,MU6873CGE,Commerce,English,Private Sanstha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,27230200235,MUMBAI_DYD_URC2 ( SION ) (272302),MUMBAI CITY/SUBURBAN,ABHYUDAYA EDUCATION SOCIETY'S HIGH SCHOOL (MAR...,Co-Ed,MU6792CGE,Commerce,English,Private Sanstha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,27230300307,MUMBAI_DYD_URC3 ( GHATKOPAR ) (272303),MUMBAI CITY/SUBURBAN,"AFAC ENGLISH SCHOOL , Justice Dudhat Chowk, M....",Co-Ed,MU6871CGE,Commerce,English,Private Sanstha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,27230500217,MUMBAI_DYD_URC5 ( ANDHERI ) (272305),MUMBAI CITY/SUBURBAN,"AIRPORT HIGH SCHOOL AND JUNIOR COLLEGE , New A...",Co-Ed,MU7069CGE,Commerce,English,Private Sanstha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,27230100966,MUMBAI_DYD_URC1 ( GRANT ROAD ) (272301),MUMBAI CITY/SUBURBAN,ANJUMAN-I-ISLAM'S AKBAR PEERBHOY COLLEGE OF CO...,Co-Ed,MU6748CGE,Commerce,English,Private Sanstha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df.describe()

,Sr No,UDISE,Intake,Total Fee,SC,ST,VJA,NTB,NTC,NTD,OBC,SBC,SEBC,EWS,Management,Inhouse,General
count,126.000000,1.260000e+02,126.000000,126.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,63.500000,2.723036e+10,342.936508,838.587302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,36.517119,1.892082e+05,298.468270,1443.460848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,2.723010e+10,40.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,32.250000,2.723020e+10,160.000000,300.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,63.500000,2.723040e+10,240.000000,300.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,94.750000,2.723050e+10,480.000000,715.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,126.000000,2.723070e+10,1440.000000,11000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
collegename=df["College Name"]
print(collegename)

0       NATIONAL SARVODAYA JR COLLEGE OF COMMERCE AND...
1      ABHYUDAYA EDUCATION SOCIETY'S HIGH SCHOOL (MAR...
2      AFAC ENGLISH SCHOOL , Justice Dudhat Chowk, M....
3      AIRPORT HIGH SCHOOL AND JUNIOR COLLEGE , New A...
4      ANJUMAN-I-ISLAM'S AKBAR PEERBHOY COLLEGE OF CO...
                             ...
121    VANI VIDYALAYA & JR. COLLEGE, MULUND (W) , VAN...
122    VERSOVA WELFARE ASSOCIATION HIGH SCHOOL & JUNI...
123    VIDYANIDHI K.R. JR. COLLEGE OF COMMERCE ANDHER...
124    VIKAS HIGH SCHOOL & JR. COLLEGE, VIKHROLI (E)....
125    YASHWANT CHANDJI SAWANT VIDYAMANDIR & JR. COLL...
Name: College Name, Length: 126, dtype: object

In [32]:
print(df[df["Total Fee"]<300]["College Name"])

100    SIES COLLEGE OF COMMERCE & ECONOMICS , PLOT 71...
118    TULSI HINDI MADHYAMIK VIDYALAYA AND JUNIOR COL...
122    VERSOVA WELFARE ASSOCIATION HIGH SCHOOL & JUNI...
Name: College Name, dtype: object

In [33]:
df.columns()

TypeError: 'Index' object is not callable

In [34]:
df.columns

Index(['Sr No', 'UDISE', 'Area', 'District', 'College Name', 'College Type',
       'Choice Code', 'Stream', 'Medium', 'Management Type', 'Intake',
       'Total Fee', 'SC', 'ST', 'VJA', 'NTB', 'NTC', 'NTD', 'OBC', 'SBC',
       'SEBC', 'EWS', 'Management', 'Inhouse', 'General'],
      dtype='object')

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Sr No            126 non-null    int64
 1   UDISE            126 non-null    int64
 2   Area             126 non-null    object
 3   District         126 non-null    object
 4   College Name     126 non-null    object
 5   College Type     126 non-null    object
 6   Choice Code      126 non-null    object
 7   Stream           126 non-null    object
 8   Medium           126 non-null    object
 9   Management Type  126 non-null    object
 10  Intake           126 non-null    int64
 11  Total Fee        126 non-null    int64
 12  SC               0 non-null      float64
 13  ST               0 non-null      float64
 14  VJA              0 non-null      float64
 15  NTB              0 non-null      float64
 16  NTC              0 non-null      float64
 17  NTD              0 non-null      float64
 18  OBC              0 non-null      float64
 19  SBC              0 non-null      float64
 20  SEBC             0 non-null      float64
 21  EWS              0 non-null      float64
 22  Management       0 non-null      float64
 23  Inhouse          0 non-null      float64
 24  General          0 non-null      float64
dtypes: float64(13), int64(4), object(8)
memory usage: 24.7+ KB

In [43]:
test=df[df["Intake"]==300]["College Name"]
print(test)

13    BURHANI COLLEGE OF COMM.& ARTS , 10 NESBIT RD ...
Name: College Name, dtype: object

In [47]:
import pandas as pd
df=pd.read_csv(r"C:\Users\sarve\Downloads\archive\deliveries.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [48]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [51]:
df["extra_runs"]

0         1
1         0
2         1
3         0
4         0
         ..
260915    0
260916    0
260917    0
260918    0
260919    0
Name: extra_runs, Length: 260920, dtype: int64